// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: family_link.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createFamilyLink = `-- name: CreateFamilyLink :one
INSERT INTO family_links (child_id, parent_id)
VALUES ($1, $2)
RETURNING id, child_id, parent_id, created_at
`

type CreateFamilyLinkParams struct {
	ChildID  uuid.UUID `json:"child_id"`
	ParentID uuid.UUID `json:"parent_id"`
}

func (q *Queries) CreateFamilyLink(ctx context.Context, arg CreateFamilyLinkParams) (FamilyLink, error) {
	row := q.db.QueryRow(ctx, createFamilyLink, arg.ChildID, arg.ParentID)
	var i FamilyLink
	err := row.Scan(
		&i.ID,
		&i.ChildID,
		&i.ParentID,
		&i.CreatedAt,
	)
	return i, err
}
