// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type FamilyLink struct {
	ID        uuid.UUID `json:"id"`
	ChildID   uuid.UUID `json:"child_id"`
	ParentID  uuid.UUID `json:"parent_id"`
	CreatedAt time.Time `json:"created_at"`
}

type PairingCode struct {
	ID        uuid.UUID          `json:"id"`
	Code      string             `json:"code"`
	ParentID  uuid.UUID          `json:"parent_id"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type PillSchedule struct {
	ID        uuid.UUID     `json:"id"`
	ParentID  uuid.UUID     `json:"parent_id"`
	PillName  string        `json:"pill_name"`
	Times     []pgtype.Time `json:"times"`
	Active    bool          `json:"active"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}
