// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pairing.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPairingCode = `-- name: CreatePairingCode :one
INSERT INTO pairing_codes (code, parent_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, code, parent_id, expires_at, used_at, created_at
`

type CreatePairingCodeParams struct {
	Code      string    `json:"code"`
	ParentID  uuid.UUID `json:"parent_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePairingCode(ctx context.Context, arg CreatePairingCodeParams) (PairingCode, error) {
	row := q.db.QueryRow(ctx, createPairingCode, arg.Code, arg.ParentID, arg.ExpiresAt)
	var i PairingCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ParentID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPairingCodeByCode = `-- name: GetPairingCodeByCode :one
SELECT id, code, parent_id, expires_at, used_at, created_at FROM pairing_codes WHERE code = $1
`

func (q *Queries) GetPairingCodeByCode(ctx context.Context, code string) (PairingCode, error) {
	row := q.db.QueryRow(ctx, getPairingCodeByCode, code)
	var i PairingCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ParentID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const redeemPairingCode = `-- name: RedeemPairingCode :one
UPDATE pairing_codes
SET used_at = now()
WHERE code = $1 AND used_at IS NULL AND expires_at > now()
RETURNING id, code, parent_id, expires_at, used_at, created_at
`

func (q *Queries) RedeemPairingCode(ctx context.Context, code string) (PairingCode, error) {
	row := q.db.QueryRow(ctx, redeemPairingCode, code)
	var i PairingCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ParentID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
