// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateFamilyLink(ctx context.Context, arg CreateFamilyLinkParams) (FamilyLink, error)
	CreatePairingCode(ctx context.Context, arg CreatePairingCodeParams) (PairingCode, error)
	GetPairingCodeByCode(ctx context.Context, code string) (PairingCode, error)
	RedeemPairingCode(ctx context.Context, code string) (PairingCode, error)
}

var _ Querier = (*Queries)(nil)
